image: scalecommerce/xenial:1.12

stages:
  - OpenJDK 8
  # - OpenJDK 11
  - Oracle Java 8
  - Oracle Java 11
  - push2github

trusty:oracle8:
  image: scalecommerce/base:0.6
  stage: Oracle Java 8
  allow_failure: true
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: oracle/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 8/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*java version \"1.8\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

trusty:oracle11:
  image: scalecommerce/base:0.6
  stage: Oracle Java 11
  allow_failure: true
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: oracle/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 11/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*java version \"11\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

xenial:openjdk8:
  image: scalecommerce/xenial:1.12
  stage: OpenJDK 8
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: openjdk/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 8/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*openjdk version \"1.8\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

xenial:oracle8:
  image: scalecommerce/xenial:1.12
  stage: Oracle Java 8
  allow_failure: true
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: oracle/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 8/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*java version \"1.8\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

xenial:oracle11:
  image: scalecommerce/xenial:1.12
  stage: Oracle Java 11
  allow_failure: true
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: oracle/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 11/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*java version \"11\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

bionic:openjdk8:
  image: scalecommerce/bionic:1.0
  stage: OpenJDK 8
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: openjdk/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 8/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*openjdk version \"1.8\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

bionic:openjdk11:
  image: scalecommerce/bionic:1.0
  stage: OpenJDK 11
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: openjdk/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 11/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*openjdk version \"11\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - java -version
    - inspec exec ./test/inspec/sc_java.rb

bionic:oracle8:
  image: scalecommerce/bionic:1.0
  stage: Oracle Java 8
  allow_failure: true
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: oracle/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 8/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*java version \"1.8\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

bionic:oracle11:
  image: scalecommerce/bionic:1.0
  stage: Oracle Java 11
  allow_failure: true
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - "sed -i 's/sc_java::java_distribution:.*/sc_java::java_distribution: oracle/' ./test/hieradata/module.yaml"
    - "sed -i 's/java_version:.*/java_version: 11/' ./test/hieradata/module.yaml"
    - sed -i "s/should match '.*'/should match '\/*java version \"11\/*'/" ./test/inspec/sc_java.rb
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_java.rb

push2github:
  stage: push2github
  script:
    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_java.git
